import type { Metadata } from 'next';
import { Jost } from 'next/font/google';
import './globals.css';

const font = Jost({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin-ext']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
